import type { Metadata } from "next";
import "./globals.css";
import { inter } from "./ui/fonts";
import "@/app/i18n";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased bg-gray-100 flex justify-center`}
      >
        <div
          className=" w-full 
              max-w-[420px]
              sm:max-w-[480px]
              md:max-w-[560px]
              lg:max-w-[640px]
              xl:max-w-[720px]
              min-h-screen"
        >
          {children}
        </div>
      </body>
    </html>
  );
}
