import { hasLocale, Locale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { inter } from "./ui/fonts";
import type { Metadata } from "next";
import { routing } from "@/i18n/routing";
import { setRequestLocale } from "next-intl/server";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
/**
 * 多语言的布局，必须要放在[lang]下多语言才生效
 * @param props
 * @returns
 */
export default async function LocaleLayout({
  children,
  params,
}: LayoutProps<"/[locale]">) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  setRequestLocale(locale);
  return (
    <>
      <html lang={locale}>
        <body
          className={`${inter.className} antialiased bg-gray-100 flex justify-center`}
        >
          <div
            className=" w-full 
                  max-w-[420px]
                  sm:max-w-[480px]
                  md:max-w-[560px]
                  lg:max-w-[640px]
                  xl:max-w-[720px]
                  h-screen bg-white"
          >
            <NextIntlClientProvider>{children}</NextIntlClientProvider>
          </div>
        </body>
      </html>
    </>
  );
}
