import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { i18n, type Locale } from "@/i18n-config";
import "./globals.css";
import { inter } from "../[lang]/ui/fonts";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}
interface IProps {
  children: React.ReactNode;
  params: Promise<{ lang: Locale }>;
}
export default async function LocaleLayout(props: IProps) {
  const params = await props.params;

  const { children } = props;

  return (
    <html lang={params.lang}>
      <body
        className={`${inter.className} antialiased bg-gray-100 flex justify-center`}
      >
        <NextIntlClientProvider locale={params.lang}>
          <div
            className=" w-full 
              max-w-[420px]
              sm:max-w-[480px]
              md:max-w-[560px]
              lg:max-w-[640px]
              xl:max-w-[720px]
              h-screen bg-white"
          >
            {children}
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
