import { hasLocale, Locale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";

import type { Metadata } from "next";
import { routing } from "@/i18n/routing";
import { setRequestLocale } from "next-intl/server";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface IProps {
  children: React.ReactNode;
  params: Promise<{ lang: Locale }>;
}
/**
 * 多语言的布局，必须要放在[lang]下多语言才生效
 * @param props
 * @returns
 */
export default async function LocaleLayout(props: IProps) {
  const params = await props.params;

  const { children } = props;
  const { lang } = await params;
  if (!hasLocale(routing.locales, lang)) {
    notFound();
  }
  setRequestLocale(lang);
  return (
    <>
      <NextIntlClientProvider>{children}</NextIntlClientProvider>
    </>
  );
}
