import { hasLocale, Locale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import "./globals.css";
import { inter } from "../[lang]/ui/fonts";
import type { Metadata } from "next";
import { routing } from "@/i18n/routing";
import { setRequestLocale } from "next-intl/server";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface IProps {
  children: React.ReactNode;
  params: Promise<{ lang: Locale }>;
}
export default async function LocaleLayout(props: IProps) {
  const params = await props.params;

  const { children } = props;
  const { lang } = await params;
  if (!hasLocale(routing.locales, lang)) {
    notFound();
  }
  setRequestLocale(lang);
  return (
    <html lang={params.lang}>
      <body
        className={`${inter.className} antialiased bg-gray-100 flex justify-center`}
      >
        <NextIntlClientProvider>
          <div
            className=" w-full 
              max-w-[420px]
              sm:max-w-[480px]
              md:max-w-[560px]
              lg:max-w-[640px]
              xl:max-w-[720px]
              h-screen bg-white"
          >
            {children}
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
